pipeline {

    agent any

    environment{
        image_name = "doan-fe"
        image_version = "1.0.0"
        docker_registry = "hai0110"
    }

    stages{
        stage("1. Clone code"){
            steps{
                echo "Clone repository..."
                checkout scm
                sh "pwd"
                sh "ls"
                echo "Clone complete!"
            }
        }

        stage("2. Build images"){
            steps{
                sh "docker build -t ${image_name}:${image_version} -f cicd/Dockerfile ."
                sh "docker tag ${image_name}:${image_version} ${docker_registry}/${image_name}:${image_version}"
            }
        }

        stage("3. Push images"){
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin"
                    sh "docker push ${docker_registry}/${image_name}:${image_version}"
                }
                
            }
        }
    }
}